logging:
  level:
    root: info
    kr.co.lotteOn: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    algorithm: PBEWithMD5AndDES
    bean: jasyptStringEncryptor

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

server:
  port: 8081
  servlet:
    context-path: /

spring:
  data:
    redis:
      host: 54.180.162.217
      port: 6379
      timeout: 6000

  servlet:
    multipart:
      location: uploads
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: wnstj050505@gmail.com
    password: yhrh mdjx drdo ithj
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  application:
    name: lotteOn
    version: SNAPSHOT

  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: HTML
    cache: false

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true

  datasource:
    url: jdbc:mysql://54.180.162.217:3306/lotteOn?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Qwerty@123
    driver-class-name: com.mysql.cj.jdbc.Driver

    logging:
      level:
        com.zaxxer.hikari.HikariConfig: DEBUG
        com.zaxxer.hikari: TRACE

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ENC('ZD9s4Pr2Zb4cy3JCsWhFfXeQOsyODwqPCN2yR/q5WcQ=')
            client-secret: ENC('YqfbD3pIjAWfDjQPcDfGo+TC+KHNDX0t')
            redirect-uri: https://lotteon.online/login/oauth2/code/naver
            scope:
              - name
              - email
              - mobile
              - gender
            authorization-grant-type: authorization_code
            client-name: Naver

          google:
            client-id: ENC('/lw+h+X+ONh9zuLC4MNheKL2Vnrl0dI12Jp2HdaQVYDFmTZoQpTS0cBinBtUv4bp2IVzpHLNWQOylax36zMvjXhxAIgeioSDQIcX9WLd11l0b4DYHidcEA==')
            client-secret: ENC('+FkZqfhR+MAxMOjYvrmiYYqMAE8f6DLc4PsVPWog6EKGBvQzqS+eU3M2GROC+VLZ')
            redirect-uri: https://lotteon.online/login/oauth2/code/google
            scope:
              - email
              - profile

          kakao:
            client-id: ENC('oaAexC4IIJ14CHKf6UwU2hoTHyGqUPSqsi68MUyRA9vkEOVZ1UKiVA/BgRMvNV1V')
            client-secret:
            redirect-uri: https://lotteon.online/login/oauth2/code/kakao
            scope:
              - account_email
            authorization-grant-type: authorization_code
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id